### ISSUE TITLE
organisera lite bland filerna för att kunna hitta lättare

### ISSUE THREAD

**Issue by pappewaio** [hannabjorck/jesper#3]
Jag föreslår att vi skapar en mapp där du kan ha dina funktioner och en mapp där du kan ha dina specifika analyser. Låt mig organisera så kan du inspektera efteråt. Det som är farligt med detta är att det bryter en del "paths" (sv. sökvägar) till filer som läses in eller skrivs ut såsom pdfs. Men eftersom det just nu inte är så många så går det enkelt att manuellt ändra. Jag gör det också.

**Comment by hannabjorck** [comment]
Ok. Jag litar på dig.

Med vänlig hälsning,
Jasmin
